### ISSUE TITLE
Рефакторинг

### ISSUE THREAD

**Issue by sdnv0x4d** [sdnv77/wol_mikrotik#1]
В данной реализации на каждый хост поднимается отдельное SSH-подключение.
Нужно отсылать пакеты в одном подключении.

**Comment by sdnv77** [comment]
Added index array for all wol commands. Now using 1 ssh-connection and multiple commands in it.

**Comment by sdnv0x4d** [comment]
Added index array for all wol commands. Now using 1 ssh-connection and multiple commands in it.
